package com.bw.arp.jd.greendemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.arp.jd.HomePage.Sousuo.bean.mysousuogreendao.KeyWordBean;

import com.bw.arp.jd.greendemo.KeyWordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyWordBeanDaoConfig;

    private final KeyWordBeanDao keyWordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyWordBeanDaoConfig = daoConfigMap.get(KeyWordBeanDao.class).clone();
        keyWordBeanDaoConfig.initIdentityScope(type);

        keyWordBeanDao = new KeyWordBeanDao(keyWordBeanDaoConfig, this);

        registerDao(KeyWordBean.class, keyWordBeanDao);
    }
    
    public void clear() {
        keyWordBeanDaoConfig.clearIdentityScope();
    }

    public KeyWordBeanDao getKeyWordBeanDao() {
        return keyWordBeanDao;
    }

}
